nohup: ignoring input
/home/lab416/anaconda3/envs/pt37/bin/python: can't open file 'train.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/lab416/anaconda3/envs/pt37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lab416/anaconda3/envs/pt37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lab416/anaconda3/envs/pt37/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/lab416/anaconda3/envs/pt37/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/lab416/anaconda3/envs/pt37/bin/python', '-u', 'train.py', '--local_rank=2', '--config', 'configs/imagenet/resnet_preact_18.yaml', 'train.output_dir', 'experiments/preresnet18_3atan_0o5', 'train.distributed', 'True', 'train.dataloader.pin_memory', 'True', 'train.resume', 'True']' returned non-zero exit status 2.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/lab416/anaconda3/envs/pt37/bin/python: can't open file 'train.py': [Errno 2] No such file or directory
/home/lab416/anaconda3/envs/pt37/bin/python: can't open file 'train.py': [Errno 2] No such file or directory
